//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 06/04/2018 22:52:27
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace LottoryUWP.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public sealed partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        static Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Let¡®s Lucky Draw, who is the next winner?"
        /// </summary>
        public static string AppDescription
        {
            get
            {
                return resourceLoader.GetString("AppDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Let¡®s Lucky Draw"
        /// </summary>
        public static string AppName
        {
            get
            {
                return resourceLoader.GetString("AppName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Not Now"
        /// </summary>
        public static string ContentDialog_ResetAll_NO
        {
            get
            {
                return resourceLoader.GetString("ContentDialog_ResetAll_NO");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Restart"
        /// </summary>
        public static string ContentDialog_ResetAll_OK
        {
            get
            {
                return resourceLoader.GetString("ContentDialog_ResetAll_OK");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Contiune"
        /// </summary>
        public static string DataSetting_Dialog_Contiune
        {
            get
            {
                return resourceLoader.GetString("DataSetting_Dialog_Contiune");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Error"
        /// </summary>
        public static string DataSetting_Dialog_Error
        {
            get
            {
                return resourceLoader.GetString("DataSetting_Dialog_Error");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "This file exceed 200 contents limitation, please check the file again."
        /// </summary>
        public static string DataSetting_Dialog_Exceed
        {
            get
            {
                return resourceLoader.GetString("DataSetting_Dialog_Exceed");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "We are unable to read the file, please check the file format!"
        /// </summary>
        public static string DataSetting_Dialog_FileError
        {
            get
            {
                return resourceLoader.GetString("DataSetting_Dialog_FileError");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No"
        /// </summary>
        public static string DataSetting_Dialog_No
        {
            get
            {
                return resourceLoader.GetString("DataSetting_Dialog_No");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "OK"
        /// </summary>
        public static string DataSetting_Dialog_Ok
        {
            get
            {
                return resourceLoader.GetString("DataSetting_Dialog_Ok");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The changes will reload data source and clear all current draw history, do you want to continue?"
        /// </summary>
        public static string DataSetting_Dialog_Reload
        {
            get
            {
                return resourceLoader.GetString("DataSetting_Dialog_Reload");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Warning"
        /// </summary>
        public static string DataSetting_Dialog_Warning
        {
            get
            {
                return resourceLoader.GetString("DataSetting_Dialog_Warning");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Comma delimited CSV (UTF-8)"
        /// </summary>
        public static string DataSetting_FileType
        {
            get
            {
                return resourceLoader.GetString("DataSetting_FileType");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Starting {0} | {1}"
        /// </summary>
        public static string InfoBaar_Starting
        {
            get
            {
                return resourceLoader.GetString("InfoBaar_Starting");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Applied Group Capacity {0}"
        /// </summary>
        public static string InfoBar_Capacity_Applied
        {
            get
            {
                return resourceLoader.GetString("InfoBar_Capacity_Applied");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Free Draw"
        /// </summary>
        public static string InfoBar_Capacity_FreeDraw
        {
            get
            {
                return resourceLoader.GetString("InfoBar_Capacity_FreeDraw");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "{0} | {1}"
        /// </summary>
        public static string InfoBar_Default
        {
            get
            {
                return resourceLoader.GetString("InfoBar_Default");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "{0} out of {1} Lucky Winner(s)"
        /// </summary>
        public static string InfoBar_DrawInfo_Capacity
        {
            get
            {
                return resourceLoader.GetString("InfoBar_DrawInfo_Capacity");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "{0} Lucky Winner(s)"
        /// </summary>
        public static string InfoBar_DrawInfo_FreeDraw
        {
            get
            {
                return resourceLoader.GetString("InfoBar_DrawInfo_FreeDraw");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "{0} | {1} | {2}"
        /// </summary>
        public static string InfoBar_Running
        {
            get
            {
                return resourceLoader.GetString("InfoBar_Running");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Next: {0} | {1}"
        /// </summary>
        public static string InfoBar_Stopped
        {
            get
            {
                return resourceLoader.GetString("InfoBar_Stopped");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Report Date"
        /// </summary>
        public static string Report_Date
        {
            get
            {
                return resourceLoader.GetString("Report_Date");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Index"
        /// </summary>
        public static string Report_Index
        {
            get
            {
                return resourceLoader.GetString("Report_Index");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Winner Ratio"
        /// </summary>
        public static string Report_Ratio
        {
            get
            {
                return resourceLoader.GetString("Report_Ratio");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Time Stamp"
        /// </summary>
        public static string Report_TimeStamp
        {
            get
            {
                return resourceLoader.GetString("Report_TimeStamp");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Event Report"
        /// </summary>
        public static string Report_Title
        {
            get
            {
                return resourceLoader.GetString("Report_Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Total Audiance"
        /// </summary>
        public static string Report_Total_Audiance
        {
            get
            {
                return resourceLoader.GetString("Report_Total_Audiance");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Total Round"
        /// </summary>
        public static string Report_Total_Round
        {
            get
            {
                return resourceLoader.GetString("Report_Total_Round");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Total Winner"
        /// </summary>
        public static string Report_Total_Winner
        {
            get
            {
                return resourceLoader.GetString("Report_Total_Winner");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "We will restart the application to reset all settings"
        /// </summary>
        public static string Restart_App_Reset
        {
            get
            {
                return resourceLoader.GetString("Restart_App_Reset");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Visual Appearance"
        /// </summary>
        public static string SettingTitle_Event_Appearance
        {
            get
            {
                return resourceLoader.GetString("SettingTitle_Event_Appearance");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Data Source"
        /// </summary>
        public static string SettingTitle_Event_Data
        {
            get
            {
                return resourceLoader.GetString("SettingTitle_Event_Data");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Misc"
        /// </summary>
        public static string SettingTitle_Event_Support
        {
            get
            {
                return resourceLoader.GetString("SettingTitle_Event_Support");
            }
        }
    }
}
